name: todo_fui
description: ToDo List – things are fine.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: 2.0.7
  provider: ^6.1.5
  
  # Navigation
  go_router: ^16.0.0
  
  # Local Storage for settings
  get_storage: ^2.1.1
  
  # Theme generator
  theme_tailor_annotation: ^3.0.2

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  firebase_storage: ^12.4.9
  cloud_firestore: ^5.6.11

  # Google Sign In
  google_sign_in: ^7.1.1
  google_sign_in_web: ^1.0.0

  # Local Notifications
  # flutter_local_notifications: ^19.3.1
  flutter_timezone: ^4.1.1
  timezone: ^0.10.1

  # Device info
  device_info_plus: ^11.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Build runner
  build_runner: ^2.5.4
  # Theme generator
  theme_tailor: ^3.0.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic

flutter_intl:
  enabled: true
