name: todo_fui
description: ToDo List – things are fine.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  provider: ^6.1.5
  
  # Navigation
  go_router: ^16.2.4
  
  # Local Storage for settings
  get_storage: ^2.1.1
  
  # Theme generator
  theme_tailor_annotation: ^3.1.1

  # Freezed
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  cloud_firestore: ^6.0.2

  # Google Sign In
  google_sign_in: ^7.2.0
  google_sign_in_web: ^1.1.0

  # Local Notifications
  # flutter_local_notifications: ^19.3.1
  flutter_timezone: ^5.0.0
  timezone: ^0.10.1

  # Device info
  device_info_plus: ^12.1.0

  # Utils
  uuid: ^4.5.1
  app_settings: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Build runner
  build_runner: ^2.9.0
  # Theme generator
  theme_tailor: ^3.1.1
  # Freezed
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic

flutter_intl:
  enabled: true
